### PR TITLE
Add bower to devdependencies

### PR DESCRIPTION
**Pull request by anagramik**
Adding **bower** to ***package.json***. It's just a thought...  For people who don't have it installed globally. If you add this then they can fallow the installation process `npm intall`, `bower instal` with not abstractions. Again, it's just a thought...

### CODE REVIEW

**Comment by oriSomething** [comment]
why?

**Comment by anagramik** [comment]
I was new to this theme (unstable version of html5blank) and when I
fallowed the steps I got "bower command not found" because I didn't had it
installed globally. It's really not that big of a deal but I just thought
it might be useful.

**Comment by oriSomething** [comment]
it's not. you should install bower globally
```
npm i -g bower
```

**Comment by toddmotto** [comment]
Yes, recommended for global install. We should move to `npm` really.

**Comment by oriSomething** [comment]
@toddmotto easy to say, but most WP programmers have troubles with `npm i && bower i`. i'm not sure really if it make good for none JS devs. but if do this, we might also move to webpack and the we can also remove both gulp, livereload and bower

**Comment by toddmotto** [comment]
I'd be open to that, I can't think WP tooling will be as stagnant as it has been forever, some form of JS powered tooling would be awesome.

**Comment by oriSomething** [comment]
@toddmotto since node require bundling anyway… webpack or you prefer browserify? with webpack... we'll pretty much only need npm scripts + webpack. with browserify we'll still need gulp

**Comment by toddmotto** [comment]
2016 seems to be going npm scripts + webpack, I think we should match that
expectation.

On 4 February 2016 at 20:29, ori livni <notifications@github.com> wrote:

> @toddmotto <https://github.com/toddmotto> since node require bundling
> anyway… webpack or you prefer browserify? with webpack... we'll pretty much
> only need npm scripts + webpack. with browserify we'll still need gulp
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/toddmotto/html5blank/pull/126#issuecomment-180033004>.
>



-- 
@toddmotto

**Pull request closed without merging**
