### PR TITLE
Update functions.php

### PR DESCRIPTION
**Pull request by pandory-network**
add option HTML5 support

### CODE REVIEW

**Comment by oriSomething** [comment]
1. i think it's time to make this as default
2. don't put `( extra space )`. because other functions `(don't)`

**Comment by pandory-network** [comment]
Extra Spaces now removed
i think html5 support optional, not all browser(versions) support html5 full

**Comment by oriSomething** [comment]
actually, it's not accurate. the tags are not supported, and this is why we use `normalize.css` and `modernizr`. it will parse just as fine as a modern browser. and if you use the right CSS, it would render the same. it's true if you turn JS off it's a problem, but i don't think anyone here is making website for `IE 6.0 + no JS` users.

i recommend to you to watch this [video](https://www.youtube.com/watch?v=WxmcDoAxdoY).

**Comment by oriSomething** [comment]
I will rebase it with some fixes (don't worry the name of the PR will be yours)

**Comment by oriSomething** [comment]
In the end I've only added a fix upon the commit.

Thanks

**Pull request merged**
