### PR TITLE
style.css

### PR DESCRIPTION
**Pull request by jKratzik**
Added accessibility classes and empty class names (for now according WordPress theme submission guidelines)

### CODE REVIEW

**Comment by grischka** [comment]
Style.css is being compiled using sass. So please add changes accordingly to scss files

**Comment by jKratzik** [comment]
@grischka thanks for referring me to SASS!
I am checking the theme right now against errors (like the missing CSS/JS) files - and against official WordPress theme submission guidelines. The 3 CSS classes must be included and at the same time I took the chance to add a skip link to header.php

**Comment by grischka** [comment]
This is your file then: https://github.com/toddmotto/html5blank/blob/master/src/css/sass/partials/wordpress.scss

.sticky & .bypostauthor are there already but my guess is that they are being discarded during sass compilation as they are empty

**Comment by jKratzik** [comment]
Thanks for the hint :-)

**Pull request closed without merging**
