### PR TITLE
Fix heading on the category page

### PR DESCRIPTION
**Pull request by nhylated**
Currently, the heading on the category page is 'Categories for \<category\>' which seems incorrect. Perhaps, this was meant to be 'Posts for \<category\>'?

I've changed the heading to 'Category: \<category\>' which is consistent with the [twenty fifteen theme](https://twentyfifteendemo.wordpress.com/category/books/).

### CODE REVIEW

**Comment by oriSomething** [comment]
yep. but it also means we have to change it in all languages files (`src/langauges/*`)

**Comment by nhylated** [comment]
Ok, I'll update the files in src/languages by tomorrow.

**Comment by nhylated** [comment]
@oriSomething Language files in `src/languages` have been updated.

**Comment by oriSomething** [comment]
and thanks by the way

**Pull request merged**
